name = "cubedos"
description = "Software framework for CubSat space missions."
version = "0.1.0-dev"

authors = ["Vermont Technical College"]
maintainers = ["Vermont Technical College <example@example.com>"]
maintainers-logins = ["cubesatlab"]
[[depends-on]]
gnatprove = "^12.1.1"

[build-switches]
"*".style_checks = "No"
development.optimization = ["-gnata", "-gnatwa", "-g", "-gnatVa", "-fstack-check"]
[[depends-on]]
aunit = "^23.0.0"
