name = "echo"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Sevo"]
maintainers = ["Sevo <sgolnaza@gmail.com>"]
maintainers-logins = ["sevanbadal"]

executables = ["echo"]

[[depends-on]]
gnat_external = "^15.0.0"

[[build-switches]]
"*".ada_version = "ada2022"
