--------------------------------------------------------------------------------
-- FILE   : cubedos-%MODULENAME%-api.adb
-- SUBJECT: Body of a package that implements the %MODULENAME% API
-- AUTHOR : (C) Copyright 2018 by Vermont Technical College
--
-- All the subprograms in this package are task safe.
--
-- THIS FILE WAS GENERATED BY XDR2OS3. DO NOT EDIT!!
--------------------------------------------------------------------------------
pragma SPARK_Mode(On);

with CubedOS.Lib.XDR;
with CubedOS.Lib;
use  CubedOS.Lib;
use  CubedOS.Lib.XDR;

package body CubedOS.%MODULENAME%.API is

   %BULK%

end CubedOS.%MODULENAME%.API;
