--------------------------------------------------------------------------------
-- FILE   : cubedos-%MODULENAME%-api.ads
-- SUBJECT: Specification of a package that defines the %MODULENAME% API
-- AUTHOR : (C) Copyright 2018 by Vermont Technical College
--
-- All the subprograms in this package are task safe.
--
-- THIS FILE WAS GENERATED BY XDR2OS3. DO NOT EDIT!!
--------------------------------------------------------------------------------
pragma SPARK_Mode(On);

with CubedOS.Lib;
with Message_Manager;  use Message_Manager;
with System;

package CubedOS.%MODULENAME%.API is

   %BULK%

end CubedOS.%MODULENAME%.API;
