--------------------------------------------------------------------------------
-- FILE   : cubedos-ping_client-api.ads
-- SUBJECT: Specification of a package that defines the Ping_Client API
-- AUTHOR : (C) Copyright 2021 by Vermont Technical College
--
-- All the subprograms in this package are task safe.
--
-- THIS FILE WAS GENERATED BY Merc. DO NOT EDIT!!
--------------------------------------------------------------------------------
pragma SPARK_Mode(On);

with Name_Resolver;
with CubedOS.Lib;
with Message_Manager;  use Message_Manager;
with CubedOS.Message_Types; use CubedOS.Message_Types;
with System;

with Ping_Server.API;

package Ping_Client.API is
   This_Module : constant Module_ID_Type := Name_Resolver.Ping_Client;

   This_Receives : aliased constant Message_Type_Array := (0 => Ping_Server.API.Ping_Reply_Msg);
   Mail_Target : constant Module_Metadata := (This_Module, This_Receives'Access);

   procedure Needs_Body;

end Ping_Client.API;
